### PR TITLE
Add round sliding switch: SwitchRound

### PR DESCRIPTION
**Pull request by kmatch98**
SwitchRound
This is the introductory GUI widget using the Widget and Control classes to create a sliding switch.

### CODE REVIEW

**Comment by kmatch98** [comment]
This cleared all the checks.  If you can figure out how to access the html docs that are built, I’d appreciate that someone review those too. In particular I am hoping that the detailed description of how this switch is constructed will give a good basis for others to build on.

**Comment by FoamyGuy** [comment]
I think I know how to view the generated pages. I'll check it out tonight with the changes in this PR. If it does work how I'm thinking I can share that with you as well.

**Comment by kmatch98** [comment]
I asked about the docs because I looked at the current ReadTheDocs for this library and it still doesn’t show the Widget and Control classes that were just merged. I think I had all the correct additions in api.rst to add them but somehow it’s not showing up. Either I didn’t do it right or maybe it’s just not update over there (which seems unlikely). That’s why I wanted see how to check the build for the docs. I saw some readmes about defining GitHub “artifacts”, but sounds like you have some experience in getting this done. 

Anyway, before this gets merged I want to be sure that Widget, Control and SwitchRound docs all match what is expected (from what seems to build ok on my machine).

**Comment by FoamyGuy** [comment]
@kmatch98 I see what you mean. It does look correct to when building locally. I'm not sure why the one in readthedocs didn't update. I'm wondering if the order that things happened in the first time somehow made it out of sync. 

I'm going to get this tested out today. As long as all is well I think we can merge this and see if the docs update correctly this time. If not we can work with kattni or someone to figure out what else is needed for it.

**Review by FoamyGuy — APPROVED** [review]
This is awesome @kmatch98! The animations and easing functions are a really nice touch. 

These changes look good to me.

Tested successfully on:
```
Adafruit CircuitPython 6.2.0-beta.3-36-g103632f44 on 2021-03-07; Adafruit PyPortal with samd51j20
```
I'm going to merge this. I'll check on the docs afterward and if they don't update we can ask about it tomorrow.

**Comment by kmatch98** [comment]
Thanks a lot for the review!

**Comment by FoamyGuy** [comment]
Strange! the docs generated locally look good to me and do include all of the new things. The output I see locally matches the output for the Build docs section of Actions. As far as I can tell everything went smoothly. But the docs visible on the live page do not include any of the newer things.

**Comment by kmatch98** [comment]
That is odd.  Maybe somehow it's not getting saved and pushed over to the readthedocs site.  Seems like the same issue happend on the last merge.  Any idea who can help figure this out?

**Comment by dhalbert** [comment]
Somehow the ReadTheDocs webhook URL got set to something wrong. I have set it to the correct URL and forced a new delivery, and it rebuilt. If you could check it that would be great.

**Comment by kmatch98** [comment]
@dhalbert I followed the link on the front page of the repo and the ReadTheDocs docs are still not updated. 

Here is the web link it sent me to:
https://circuitpython.readthedocs.io/projects/displayio-layout/en/latest/

I don’t know if it’s any clue, but when I get to the RTD page, the “docs link” there is wrong and goes to nothing: 
https://circuitpython.readthedocs.io/projects/displayio_layout/en/latest/

kattni mentioned something related this last week https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_Layout/pull/7

**Pull request merged**
