### PR TITLE
Add Annotation widget

### PR DESCRIPTION
**Pull request by kmatch98**
annotation_example

Add annotation widget, this allows annotations relative to a widget or freeform.

(I messed up the previous PR, so I am adding it back here.)

### CODE REVIEW

**Comment by jposada202020** [comment]
@kmatch98 Well :), I like very much this, makes me remember matplotlib. anyway, testing this with the Cartesian plane, make me rework all the local coordinates, now cartesian widgets respond as a `widget`. I will do some more testing  if you want. Thanks

**Comment by jposada202020** [comment]
Tested in 
```python
Adafruit CircuitPython 6.2.0-beta.4 on 2021-03-18; Seeeduino Wio Terminal with samd51p19
```


image

## Testing Code
```python
from adafruit_displayio_layout.widgets.cartesian import Cartesian
import board
import displayio
from adafruit_display_text import label
from adafruit_bitmap_font import bitmap_font
import terminalio
from adafruit_displayio_layout.widgets.annotation import Annotation


MEDIUM_FONT = bitmap_font.load_font("fonts/Helvetica-Bold-16.bdf")

display = board.DISPLAY
my_group = displayio.Group(max_size=10)

car = Cartesian(x=150,
                y=40,
                display_color=0x98fb98,
                width=100,
                height=100,
                xrange=(0, 50),
                yrange=(0, 50),
                subticks=True,
                tick_color=0x44FF99,
                axes_color=0x990099,
                axes_stroke=2,
                pointer_color=0xFF4400, )

my_group.append(car)

plane_annotation = Annotation(
    widget=car,  # positions are relative to the switch
    text="widget.bounding_box",
    anchor_point=(0.0, 0.0),
    # delta_x=2,
    text_color=0xFFA500,
)
my_group.append(plane_annotation)
plane_annotation1 = Annotation(
    widget=car,  # positions are relative to the switch
    text="[0,0,150,40]",
    anchor_point=(0.0, 0.0),
    text_under=True,
    text_color=0xFFA500,
)
my_group.append(plane_annotation1)

plane_annotation2 = Annotation(
    widget=car,  # positions are relative to the switch
    text="Origin [0,0]   ",
    anchor_point=(0.0, 1.0),
    delta_y=4,
    text_under=False,
    text_color=0xFFA500,
)
my_group.append(plane_annotation2)

plot_area = Annotation(
    font=MEDIUM_FONT,
    widget=car,  # positions are relative to the switch
    text="Plot Area",
    anchor_point=(0.5, 0.5),
    position_offset=(-35, 0),
    text_under=False,
    delta_x=0,
    delta_y=0,
    line_color=0x00A5FF,
    text_color=0x00A5FF,
)
my_group.append(plot_area)

text = "Axes Y"
text_area = label.Label(terminalio.FONT,
                        text=text,
                        label_direction="UPR",
                        x=270,
                        y=120,
                        background_color=0xA5CADD,
                        color=0x6E266E,

                        )
my_group.append(text_area)

text2 = "Axes X"
text_area2 = label.Label(terminalio.FONT,
                         text=text2,
                         x=180,
                         y=180,
                         background_color=0xA5CADD,
                         color=0x6E266E,

                         )
my_group.append(text_area2)
display.show(my_group)



```

**Review by FoamyGuy — APPROVED** [review]
I tested this successfully with
```
Adafruit CircuitPython 6.2.0-beta.4 on 2021-03-18; Adafruit PyPortal with samd51j20
```
Code looks good to me.

These annotations are really great looking. I like how you allowed it to attach onto another widget. We can use this in future example scripts to highlight the features of new widgets.

Thank you @jposada202020 for testing this out as well.

**Comment by kmatch98** [comment]
I’m thinking it will be useful for GUIs that might have a “Help” or “?” Button. 

Thanks @jposada202020 and @FoamyGuy for reviewing and trying it out and merging!

**Comment by kmatch98** [comment]
And @jposada202020 i like how you did the over and under annotation. I never thought of that!

**Comment by jposada202020** [comment]
@FoamyGuy @kmatch98 Team work! :)

**Pull request merged**
