### PR TITLE
Update grid_layout.py

### PR DESCRIPTION
**Pull request by gingershaped**
Added the ability to change the divider line color

### CODE REVIEW

**Comment by FoamyGuy** [comment]
@GingerIndustries thanks for adding this functionality. This is currently failing pylint due to `too-many-instance-attributes`. apparently we were previous right at the limit, and adding the new one pushed it over.

Some of the attributes could be collapsed into a dictionary or other object that can hold multiple things. But it seems to me that this would make the code more complex for the purpose of pleasing pylint. 

Personally I think it would be okay to disable the `too-many-instance-attributes` check for this class. But I'm open to input from others. If that does turn out to be the route we want to go with, do you know how to do that @GingerIndustries?

**Comment by gingershaped** [comment]
It probably doesn't matter, as this will be compiled to an .mpy regardless. I could make the changes if you want.

**Comment by FoamyGuy** [comment]
@GingerIndustries we will have to getting passing the CI checks one way or another before it can be merged. Even though the resulting library will get compiled to mpy we still run pylint and a few other checks on the .py version of the code using github actions.

Go ahead and add the pylint disable comment for that specific check. Let me know if you have any trouble, or need help with that.

**Comment by gingershaped** [comment]
Okay, it's done.

**Review by FoamyGuy — APPROVED** [review]
Changes look good to me. Tested successfully on a PyPortal with a modified the gridlayout_dividers script in the examples directory. 

I tested hex colors i.e. `0xFF00FF` as well as tuple colors i.e `(255, 0, 255)` and both work as expected. I think internally displayio.Palette allows both to work in this case without any specific code needed in this library. 

Thanks for adding this new functionality @GingerIndustries

**Comment by gingershaped** [comment]
Nice! Thanks,

**Pull request merged**
