### PR TITLE
remove annotation and dial widgets from this repo. 

### PR DESCRIPTION
**Pull request by FoamyGuy**
This removes Annotation and Dial widgets and associated examples and documentation from this repo. These now have their own repos over in the circuitpython organization and they've both been added to the CircuitPython_Org bundle.

All of the code and documentation removed with this PR is now available in these respective repos:
https://github.com/circuitpython/CircuitPython_Org_DisplayIO_Dial
https://github.com/circuitpython/CircuitPython_Org_DisplayIO_Annotation

The other widgets that are in this repo currently will get removed as soon as they are setup in new repos in circuitpython org and added to that bundle.

This PR also updates the pylintrc file to the latest version that cookie-cutter now generates.

### CODE REVIEW

**Comment by FoamyGuy** [comment]
Forgot to mention in the original comment but I would consider #45 resolved once this is merged.

The new Dial repo has been updated already to support the latest version of the `vectorio` API

**Review by kattni — CHANGES_REQUESTED** [review]
@FoamyGuy Are there any guides/examples outside the repo that need to be updated, or were these features never used elsewhere?

**Comment by FoamyGuy** [comment]
@kattni to the best of my knowledge there are no guide or example usages of these two widgets outside of this repo. I grepped for both in the Learn guide repo and did not find any.

As far as I know the only one of the widgets that are currently in this repo that did get used for a guide / example is the IconWidget which was used in the Stream Deck project. This PR doesn't remove IconWidget, my intention there is to ensure that the project bundler used by Learn system will be able to find it properly in it's new home before removing it from here so that the transition will be seamless to folks who are following that guide.

**Review by kattni — APPROVED** [review]

**Comment by kattni** [comment]
Thanks!

**Pull request merged**
